# Generated by Django 2.2.7 on 2020-09-17 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0004_auto_20200917_1212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='quiz_name',
            field=models.CharField(default='Enter Paper Name', max_length=20),
        ),
        migrations.AlterField(
            model_name='answer',
            name='roll',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
