# Generated by Django 2.2.7 on 2020-09-24 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0006_auto_20200924_0645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='end',
            field=models.TimeField(blank=True, help_text='Enter time in 24 hour format !'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='name',
            field=models.CharField(help_text='SUBJECT NAME', max_length=255),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='start',
            field=models.TimeField(blank=True, help_text='Enter time in 24 hour format !'),
        ),
    ]
