# Generated by Django 2.2.7 on 2020-09-25 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0008_auto_20200924_2244'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='section',
            field=models.CharField(default='A', max_length=1),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='date',
            field=models.DateField(default='2020-09-25'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='today',
            field=models.DateField(default='2020-09-25'),
        ),
    ]
