# Generated by Django 2.2.7 on 2020-09-25 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0009_auto_20200925_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='quiz_name',
            field=models.CharField(default='ENTER SUBJECT', max_length=20),
        ),
    ]
